In [1]:
import pandas as pd
import gc

In [2]:
#读入整个的embedding
creative_id_embedding = pd.read_csv('output/model/creative_id_embedding.csv')
creative_id_embedding

,creative_id,creative_id_embe_0,creative_id_embe_1,creative_id_embe_2,creative_id_embe_3,creative_id_embe_4,creative_id_embe_5,creative_id_embe_6,creative_id_embe_7,creative_id_embe_8,...,creative_id_embe_22,creative_id_embe_23,creative_id_embe_24,creative_id_embe_25,creative_id_embe_26,creative_id_embe_27,creative_id_embe_28,creative_id_embe_29,creative_id_embe_30,creative_id_embe_31
0,1,-0.405547,0.725169,0.423469,0.015946,-0.008649,0.077469,-0.010404,0.375016,-0.327518,...,-0.356907,-0.165169,-0.538663,-0.234938,0.825907,0.010920,-0.641028,-0.198432,-0.762730,0.334872
1,4,-0.446732,0.927985,0.526217,0.396676,-0.221806,0.117984,0.039173,0.103609,-0.474610,...,-0.155134,0.002707,0.002844,-0.158829,0.347565,0.020952,-0.983312,-0.704252,-0.359463,-0.147971
2,7,0.087532,0.095536,-0.136538,-0.047536,-0.109545,-0.036275,0.076543,0.023173,-0.146432,...,-0.168074,-0.131901,0.040538,-0.124540,-0.007676,-0.103386,-0.149685,-0.137325,-0.124677,-0.102893
3,10,-0.295333,0.511326,0.373940,0.155660,0.040628,-0.023969,0.073726,0.011495,-0.152683,...,-0.161585,0.079991,-0.252220,-0.216957,0.420880,0.081843,-0.252303,-0.194212,-0.320472,0.274480
4,13,-0.138784,0.324466,0.243483,0.189073,0.284274,0.176511,0.122085,0.048535,-0.010649,...,-0.089465,0.017529,-0.225412,-0.026141,0.210116,-0.298794,-0.401896,-0.276365,-0.028312,0.038636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2086581,4445710,-0.064118,0.131664,0.124072,0.059363,0.010769,0.021337,0.021939,0.023574,-0.117052,...,-0.029300,0.021492,-0.065645,-0.050683,0.076507,-0.000035,-0.136281,-0.052887,-0.066511,-0.024349
2086582,4445711,-0.258697,0.148187,0.264473,0.005274,-0.019459,-0.045155,0.040560,0.147630,-0.044312,...,-0.246009,-0.164699,-0.112111,-0.126867,0.070902,-0.229397,-0.150297,-0.190123,-0.059199,0.087896
2086583,4445715,-0.082657,0.229959,0.149897,0.115988,0.000124,0.057486,-0.037380,0.089782,-0.036252,...,-0.088656,0.060387,-0.227509,-0.042947,0.101232,0.033068,-0.107275,-0.152438,-0.148029,0.086677
2086584,4445718,-0.046075,0.064836,0.140005,0.043423,0.035853,0.045022,-0.036449,0.120412,0.026136,...,-0.082540,-0.005498,-0.138193,-0.024613,0.086398,0.032175,-0.078071,-0.081085,-0.093335,0.072537
2086585,4445719,-0.081988,0.164107,0.139710,0.094169,0.048825,0.066816,-0.036260,0.086572,-0.076292,...,-0.094352,-0.001606,-0.089018,0.027996,0.064752,-0.135572,-0.159812,-0.010738,-0.135267,0.110775

训练集

In [3]:
train_click_log = pd.read_csv('data/train_preliminary/click_log.csv')
train_click_log 
# test_click_log = pd.read_csv('data/test/click_log.csv')
# train_test_click_log = train_click_log.append(test_click_log)
# train_test_features = train_test_click_log[['user_id', 'creative_id']]
# train_test_features

          time  user_id  creative_id  click_times
0            9    30920       567330            1
1           65    30920      3072255            1
2           56    30920      2361327            1
3            6   309204       325532            1
4           59   309204      2746730            1
...        ...      ...          ...          ...
30082766     6    30920       228129            1
30082767    57    30920      2361397            1
30082768    26    30920       629802            1
30082769    86    30920      2713031            1
30082770    25    30920       629802            1

[30082771 rows x 4 columns]

In [4]:
train_features = train_click_log[['user_id', 'creative_id']]
del train_click_log
gc.collect()
train_features

          user_id  creative_id
0           30920       567330
1           30920      3072255
2           30920      2361327
3          309204       325532
4          309204      2746730
...           ...          ...
30082766    30920       228129
30082767    30920      2361397
30082768    30920       629802
30082769    30920      2713031
30082770    30920       629802

[30082771 rows x 2 columns]

In [5]:
train_id = train_features[['user_id']].drop_duplicates()
train_id

          user_id
0           30920
3          309204
28         309208
39          30921
52         309215
...           ...
30082472    30919
30082562   309192
30082613   309194
30082623   309197
30082639   309198

[900000 rows x 1 columns]

In [6]:
train_creative_id_embedding = pd.merge(train_features, creative_id_embedding, on='creative_id', how='left')
train_creative_id_embedding

,user_id,creative_id,creative_id_embe_0,creative_id_embe_1,creative_id_embe_2,creative_id_embe_3,creative_id_embe_4,creative_id_embe_5,creative_id_embe_6,creative_id_embe_7,...,creative_id_embe_22,creative_id_embe_23,creative_id_embe_24,creative_id_embe_25,creative_id_embe_26,creative_id_embe_27,creative_id_embe_28,creative_id_embe_29,creative_id_embe_30,creative_id_embe_31
0,30920,567330,-1.084650,1.602850,2.818888,0.269177,3.747830,-0.809045,3.520751,0.657771,...,0.333556,-0.932272,0.461950,0.278698,0.236751,-3.218588,-6.140665,-1.657446,-1.129584,-0.111909
1,30920,3072255,-1.970147,1.271723,-2.816926,4.514661,5.487320,-6.100594,-2.661426,1.882006,...,-2.207475,-0.710228,2.117050,0.714986,2.839515,-0.292277,1.286432,2.299866,-2.059914,0.235093
2,30920,2361327,-1.564299,-0.250480,-3.972300,4.037480,1.044805,-5.623243,-3.201556,2.403929,...,-2.700711,-1.665352,0.067788,0.049849,1.049451,1.035494,0.052417,2.212894,-0.880376,-1.711696
3,309204,325532,-0.102132,0.099702,0.297197,0.095535,0.184590,0.082984,0.047868,0.219065,...,-0.082060,-0.121123,-0.044480,-0.038954,0.249979,-0.161621,-0.270083,-0.056782,-0.124920,0.110895
4,309204,2746730,-0.396516,-0.344067,0.931201,-0.784105,-0.925009,-1.439631,-0.250069,0.615499,...,-0.440745,-1.173166,0.146639,-0.138136,0.603770,-1.720428,-0.721406,0.727087,0.055398,0.888516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30082766,30920,228129,-5.923347,-1.649920,1.445602,1.020738,6.295479,0.395454,5.230465,5.587086,...,-7.945335,-6.182050,0.864321,-4.758656,2.494085,-4.246827,-3.276362,-1.797764,-1.958563,3.763632
30082767,30920,2361397,-1.955103,-0.872591,-7.440216,2.036450,2.496343,-9.206656,-1.909627,4.964462,...,-1.840462,-3.038672,1.365250,-0.862303,0.179473,5.420027,1.052177,3.160873,-1.933343,-2.702811
30082768,30920,629802,-7.313719,1.974791,0.348050,-2.223942,5.493299,-1.631434,4.558984,-1.713183,...,-3.811215,7.158753,0.729925,-1.486258,-1.114547,1.639183,2.814996,4.299975,-1.540692,-5.763409
30082769,30920,2713031,1.761943,3.101379,-4.304970,-0.642956,0.887745,-3.931121,2.556799,-7.874465,...,-3.195867,-4.176345,-3.201239,-1.034264,-0.687327,-2.777238,-1.755625,-1.747651,-6.256636,-0.878432
30082770,30920,629802,-7.313719,1.974791,0.348050,-2.223942,5.493299,-1.631434,4.558984,-1.713183,...,-3.811215,7.158753,0.729925,-1.486258,-1.114547,1.639183,2.814996,4.299975,-1.540692,-5.763409

In [7]:
def extract_feat(df_, key, name, L, train_id):
    for i in range(L):
        t = df_.groupby(key).aggregate({'{0}_embe_{1}'.format(name, i):['mean','min','max']}).reset_index()
        t.columns = ['_'.join(j).strip('_') for j in t.columns.values]
        train_id = pd.merge(train_id, t, on=key, how='left')
        del t 
        gc.collect()
    return train_id

In [8]:
train_creative_id_embedding_df= extract_feat(train_creative_id_embedding, 'user_id', 'creative_id', 32, train_id)

In [9]:
train_creative_id_embedding_df

,user_id,creative_id_embe_0_mean,creative_id_embe_0_min,creative_id_embe_0_max,creative_id_embe_1_mean,creative_id_embe_1_min,creative_id_embe_1_max,creative_id_embe_2_mean,creative_id_embe_2_min,creative_id_embe_2_max,...,creative_id_embe_28_max,creative_id_embe_29_mean,creative_id_embe_29_min,creative_id_embe_29_max,creative_id_embe_30_mean,creative_id_embe_30_min,creative_id_embe_30_max,creative_id_embe_31_mean,creative_id_embe_31_min,creative_id_embe_31_max
0,30920,-1.507675,-7.740992,4.471583,0.593262,-3.432152,5.292256,-0.907234,-7.440216,6.035981,...,5.380054,0.383888,-5.469904,4.899276,-1.374758,-6.256636,3.678530,-1.003787,-5.763409,4.011248
1,309204,-1.145303,-6.100514,1.266400,0.004501,-1.571815,2.587804,1.379954,-0.766827,6.050371,...,2.025609,0.355446,-2.209599,4.810850,-0.601605,-4.534313,2.535788,1.107402,-5.674373,5.366609
2,309208,-4.363901,-7.618531,-0.332137,0.473243,-2.847985,3.384574,1.669338,0.029908,5.137986,...,4.452756,-0.530263,-5.348944,3.672025,-0.342624,-4.558265,4.824049,0.021971,-5.910691,3.475924
3,30921,1.794596,-1.707126,7.691508,0.147661,-2.696099,3.513994,-1.969174,-7.775621,2.023383,...,2.800171,-0.016843,-4.380246,4.462756,-1.333195,-4.273919,2.115962,-0.627954,-5.356576,3.308718
4,309215,-0.101868,-4.180879,6.350177,-1.643976,-5.585307,0.283229,1.423273,-4.160352,4.917607,...,3.880209,-0.210859,-6.611134,5.720772,1.473429,-1.617117,7.030064,-1.648280,-7.253551,3.471646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,30919,-1.130110,-7.152085,4.475574,-0.046229,-4.149307,6.932230,-1.633547,-10.488724,5.544257,...,5.726737,0.010474,-6.399808,7.310504,-0.476721,-9.222209,5.932450,-0.401801,-7.752764,4.963697
899996,309192,0.325005,-5.402220,7.975923,0.487715,-3.308916,2.782434,0.733349,-6.995539,4.242157,...,5.678328,0.267262,-3.266870,4.413051,-1.476243,-8.597493,1.614289,1.446674,-6.581099,9.473816
899997,309194,-2.187926,-3.896742,-0.342819,0.022068,-1.406483,1.848393,0.004234,-7.440216,5.528419,...,3.101395,0.368930,-2.969040,3.160873,0.040500,-2.631183,6.631583,0.635576,-2.768642,4.032357
899998,309197,-3.091466,-7.332426,-0.257181,1.884680,-0.987109,6.476053,-0.813316,-8.145773,3.960187,...,2.643114,1.004861,-4.689472,5.580755,0.728295,-1.671633,4.882751,-1.693383,-9.821720,2.365408
899999,309198,0.603155,-5.457691,7.591623,1.689159,-3.860481,8.179655,-0.114483,-7.268489,5.292392,...,6.045254,0.102231,-6.201905,5.853809,-1.218788,-8.320477,4.301220,-0.352372,-9.078370,5.672479

In [10]:
train_creative_id_embedding_df.to_csv('output/features/train/creative_id_embedding_df.csv', index=False)

In [11]:
del train_features, train_id, train_creative_id_embedding, train_creative_id_embedding_df
gc.collect()

0

测试集

In [5]:
test_click_log = pd.read_csv('data/test/click_log.csv')
test_click_log

          time  user_id  creative_id  click_times
0           20  3131989       645764            1
1           20  3131989      1027422            1
2           20  3131989      1106443            1
3           20  3131989       629802            1
4           59  3131989      2839769            1
...        ...      ...          ...          ...
33585507    16  3131989       585914            1
33585508    13  3131989       749134            1
33585509    12  3131989       589027            1
33585510    61  3131989      2404831            1
33585511    14  3131989       665822            1

[33585512 rows x 4 columns]

In [6]:
test_features = test_click_log[['user_id', 'creative_id']]
del test_click_log
gc.collect()
test_features

          user_id  creative_id
0         3131989       645764
1         3131989      1027422
2         3131989      1106443
3         3131989       629802
4         3131989      2839769
...           ...          ...
33585507  3131989       585914
33585508  3131989       749134
33585509  3131989       589027
33585510  3131989      2404831
33585511  3131989       665822

[33585512 rows x 2 columns]

In [7]:
test_id = test_features[['user_id']].drop_duplicates()
test_id

          user_id
0         3131989
11        3131990
52        3131994
65        3131995
82        3132000
...           ...
33585384  3131979
33585421  3131983
33585431  3131984
33585456  3131987
33585471  3131988

[1000000 rows x 1 columns]

In [6]:
test_creative_id_embedding = pd.merge(test_features[0:12000000], creative_id_embedding, on='creative_id', how='left')
test_creative_id_embedding.to_csv('output/temp/test_creative_id_embedding_0.csv',index=False)
del test_creative_id_embedding
gc.collect()

0

In [7]:
test_creative_id_embedding = pd.merge(test_features[12000000:24000000], creative_id_embedding, on='creative_id', how='left')
test_creative_id_embedding.to_csv('output/temp/test_creative_id_embedding_1.csv',index=False)
del test_creative_id_embedding
gc.collect()

0

In [6]:
test_creative_id_embedding = pd.merge(test_features[24000000:],creative_id_embedding, on='creative_id', how='left')
test_creative_id_embedding.to_csv('output/temp/test_creative_id_embedding_2.csv',index=False)
del test_creative_id_embedding
gc.collect()

0

In [2]:
temp0=pd.read_csv('output/temp/test_creative_id_embedding_0.csv')
temp1=pd.read_csv('output/temp/test_creative_id_embedding_1.csv')
temp2=pd.read_csv('output/temp/test_creative_id_embedding_2.csv')
test_creative_id_embedding=pd.concat([temp0,temp1,temp2],ignore_index=True)
test_creative_id_embedding.to_csv('output/features/test/test_creative_id_embedding.csv')
del temp0,temp1,temp2
gc.collect()

0

In [3]:
def extract_feat(df_, key, name, L, train_id):
    for i in range(L):
        t = df_.groupby(key).aggregate({'{0}_embe_{1}'.format(name, i):['mean','min','max']}).reset_index()
        t.columns = ['_'.join(j).strip('_') for j in t.columns.values]
        train_id = pd.merge(train_id, t, on=key, how='left')
        del t 
        gc.collect()
    return train_id

In [8]:
test_creative_id_embedding_df = extract_feat(test_creative_id_embedding, 'user_id', 'creative_id', 32, test_id)
test_creative_id_embedding_df

,user_id,creative_id_embe_0_mean,creative_id_embe_0_min,creative_id_embe_0_max,creative_id_embe_1_mean,creative_id_embe_1_min,creative_id_embe_1_max,creative_id_embe_2_mean,creative_id_embe_2_min,creative_id_embe_2_max,...,creative_id_embe_28_max,creative_id_embe_29_mean,creative_id_embe_29_min,creative_id_embe_29_max,creative_id_embe_30_mean,creative_id_embe_30_min,creative_id_embe_30_max,creative_id_embe_31_mean,creative_id_embe_31_min,creative_id_embe_31_max
0,3131989,-2.858431,-7.616931,0.792602,0.613408,-1.552967,3.531705,0.913798,-2.349010,3.821316,...,3.038024,1.976224,-0.028898,5.690092,-1.668653,-6.759124,1.042463,0.722587,-5.763409,5.380659
1,3131990,-0.670124,-7.454170,4.558365,3.847051,-0.087677,11.236959,0.702059,-3.802535,6.936474,...,3.535837,0.757446,-10.144973,8.155861,-1.036780,-6.080978,6.767617,-1.493970,-6.265074,3.422250
2,3131994,-0.051410,-1.514083,3.433381,0.758244,-0.969918,4.868002,0.076572,-2.268848,2.054190,...,-0.230441,0.070325,-0.503178,1.510138,-1.428576,-7.852931,-0.103232,0.794054,-0.200537,4.184621
3,3131995,-2.478154,-5.253901,1.372947,1.340936,-4.570886,6.789227,-1.087343,-8.685025,3.291955,...,5.436015,1.175349,-1.514015,4.433827,-0.746041,-3.168849,2.475967,-1.097020,-7.723289,3.608452
4,3132000,-2.319694,-7.112206,6.273732,2.279348,-2.179095,6.811656,-1.618811,-8.389686,4.970367,...,3.684711,-0.385249,-9.206388,5.062654,1.412981,-1.868881,4.087580,-1.644165,-8.504324,3.422250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,3131979,-0.495944,-7.264338,1.944947,1.091700,-4.723361,5.746027,0.698992,-9.794483,5.113791,...,7.593482,0.068470,-4.759167,4.806403,-1.219547,-5.363983,0.354599,-0.922072,-7.885400,2.922962
999996,3131983,-0.391880,-4.149678,2.619176,1.111912,-0.866018,3.502926,-0.619611,-3.139448,1.999324,...,6.435015,0.637835,-4.701754,3.770851,0.252481,-2.547215,3.390483,1.730589,-0.946135,6.814815
999997,3131984,-0.870173,-4.444462,4.323013,0.673762,-3.562151,3.840229,0.839610,-4.688480,5.943029,...,6.345436,-1.137296,-4.898088,1.221844,0.316372,-1.354440,2.068728,-1.484077,-7.549328,4.356634
999998,3131987,-0.271955,-3.403584,3.853725,-0.161290,-6.034707,3.129095,1.536992,-4.457092,5.099025,...,1.780146,1.197604,-0.701548,6.140952,0.017707,-1.839562,3.821240,2.541082,-1.427420,7.868259
999999,3131988,-0.349701,-4.747016,4.471583,1.738013,-5.517330,7.199145,-1.083954,-7.440216,3.498801,...,3.056949,2.551988,-1.844396,7.822823,-0.514125,-5.813193,4.134559,-1.579507,-6.883457,2.452036

In [9]:
test_creative_id_embedding_df.to_csv('output/features/test/creative_id_embedding_df.csv', index=False)